version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - AZURE_ENDPOINT=${AZURE_ENDPOINT}
      - AZURE_API_VERSION=${AZURE_API_VERSION}
      - AZURE_SUBSCRIPTION_KEY=${AZURE_SUBSCRIPTION_KEY}
      - AZURE_ANALYZER_ID=${AZURE_ANALYZER_ID}
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/app.db:/app/app.db
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
